In [ ]:
# Declaring variables- assigning values
x = 5
y = 10
print(x + y)

15


Functions - start with the keyword def
- syntax  

   def  function_name(): - function header  

              ....  
     
   print(function_name()) - calls the function


In [2]:
def add_two_numbers(x,y):
    z = x + y
    return z
print(add_two_numbers(30,20))

50


In [4]:
# lambda keyword- makes functions anonymous so that you don't have to declare them
y = lambda x, y: x + y
print(y(30,20))

50


LISTS
- ordered and changeable
- represented by square brackets[ ]

DICTIONARIES
- hold key-value pairs
- are unordered and  changeable
- initialized with { }

In [ ]:
# dict= {"keys": values}
my_dict={"age": 22, "birth_year":2009, "name": "Denise", "county": "Nairobi"}

In [ ]:
# dict.keys()- used to get all the keys from the dictionary
my_dict.keys()

dict_keys(['age', 'birth_year', 'name', 'county'])

In [8]:
# dict.values()- used to get all the values from the dictionary
my_dict.values()

dict_values([22, 2009, 'Denise', 'Nairobi'])

SETS
- unordered collection of unique elements i.e doesn't allow duplicates
- allows operations like union, intersection and difference

CONTROL FLOW AND BUILT-IN-FUNCTIONS


Contol Structures in Python
- If-else construct
- syntax
-       if condition:
-           statements
-       elif condition:
-           statements
-       else:
-           statements

In [14]:
def age_check(age):
    if age >=40:
        print("Mid-life Crisis Averted")
    elif age >= 30:
        print("Mid-Life Crisis Onset") 
    elif age >= 20:
        print("Late Adolescence")
    else:
        print("Invalid age")

print(age_check(75))

Mid-life Crisis Averted
None


For Construct
-

In [ ]:
for x in range (101):
    x % 2 == 0
    print(x, end = ' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 

Built-in-functions
The zip function
- use cases
-  1. combining two lists into a list of tuples
-  2. breaking a tuple into  two lists

In [19]:
# combining two lists into tuples
number = [1,2,3,4,5]
fruits = ['apple','banana','mango','orange','pear']

list(zip(number,fruits))

[(1, 'apple'), (2, 'banana'), (3, 'mango'), (4, 'orange'), (5, 'pear')]

In [22]:
# breaking a tuple into two lists
zipped = [(1, 'apple'), (2, 'banana'), (3, 'mango'), (4, 'orange'), (5, 'pear')]
number, fruit = zip(*zipped)

print(number)
print(fruit)

(1, 2, 3, 4, 5)
('apple', 'banana', 'mango', 'orange', 'pear')


Numpy
Handling arrays with Numpy
1. Single dimensional arrays
2. Two dimensional arrays
 

In [2]:
import numpy as np

# creating an array
np_array = np.array([5,10,15,20,25])
print(np_array)

[ 5 10 15 20 25]


In [3]:
# get unique values
print(np.unique(np_array))

[ 5 10 15 20 25]


In [10]:
# get standard deviation
print(round(np.std(np_array),2))


7.07


In [12]:
# get max() and min()
print(np_array.max())
print(np_array.min())

25
5


In [14]:
# 2d arrays
np_arrays_2 = np.array([[1,2,3],
                         [4,5,6]])

In [15]:
print(np_arrays_2)

[[1 2 3]
 [4 5 6]]


In [ ]:
# calculate the transpose
# transpose is when you swap the columns and rows
transpose = np_arrays_2.T
print(transpose)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
# print the shape of the array
print(np_arrays_2.shape)

(2, 3)


In [21]:
# access elements in the array through indexing
print(np_arrays_2[1,1])
print(np_arrays_2,[0,2])

5
[[1 2 3]
 [4 5 6]] [0, 2]


In [22]:
# calculating dot product
np_array = np.array([2,4,6,8,10])
dot_product = np.dot(np_array,np_array)
print(dot_product)

220


In [24]:
np_array = np.array([2,4,6])
cross_product = np.cross(np_array,np_array)
print(cross_product)

[0 0 0]


In [ ]:
# rand() function returns a random number or numbers between 0 and 1. The number of random values returned depends on the shape provided to the function. If no shape is given, just a single number is returned.
# random number
print(np.random.rand())

0.8122568311961746


In [30]:
# generate a matrix of random numbers
print(np.random.rand(3,2))

[[0.40780923 0.80096515]
 [0.12643011 0.78806531]
 [0.00487699 0.14357001]]


In [ ]:
# randint() to return random integers from low (inclusive) to high (exclusive)
# generate 2 values between 5 and 15(exclusive)
print(np.random.randint(5,15,2))

[12  7]


In [ ]:
# generate a matrix of shape(3,2) with values between 5 and 15(exclusive)
print(np.random.randint(5,15, (3,2)))

[[11 14]
 [12 11]
 [ 9  8]]


In [ ]:
# choice() function allows you to pass an array,specify how many values to sample, and decide whether sampling should be done with or without replacement
print(np.random.choice(np_array,10, replace = True))

[2 4 2 2 2 4 6 2 2 4]


In [35]:
print(np.random.choice(np_array,3, replace=False))

[2 4 6]


In [37]:
# shuffle() - randomly shuffle your array
y = [1,2,3,4,5]
np.random.shuffle(y)
print(y)

[5, 1, 2, 4, 3]


In [38]:
# seed() -used if you want the random selections to be the same every time
np.random.seed(12)

Scipy
- Python library for scientific computing
- A correlation is a numerical measure of the statistical relationship between two variables.
- To calculate the correlation between two vectors of data use with Pearson’s r-value. This value ranges between -1 and 1. Where -1 means there is a total negative correlation, 0 means no correlation, and 1 means total positive.

In [44]:
from scipy import stats
import numpy as np

array_1 = np.array([1,2,3,4,5,6])
array_2 = array_1

print(stats.pearsonr(array_1, array_2))

PearsonRResult(statistic=np.float64(1.0), pvalue=np.float64(0.0))


In [ ]:
# Normal Distribution - 
x = stats.norm.rvs(loc=0, scale=10, size=10)
print(x)

# code above uses the loc parameter as the mean, the scale as the standard deviation, and the size as the number of samples to return.

[  4.72985831  -6.81425879   2.42439497 -17.00735634   7.53142834
 -15.3472134    0.05127078  -1.2022767   -8.06981879  28.71819395]


In [54]:
# probability density function
p1 = stats.norm.pdf(x=-100, loc=0, scale=10)
p2 = stats.norm.pdf(x=0, loc=0, scale=10)

print(p1)
print(p2)

7.69459862670642e-24
0.03989422804014327


In [ ]:
#cumulative distribution function
p1 = stats.norm.cdf(x=0, loc=0, scale=10)
print(p1)

0.5


In [ ]:
# describe() function - used to calculate multiple descriptive statistics for your array
print(stats.describe(stats.norm.rvs(loc=0, scale=1, size=500)))

# The variance is the square of the standard deviation. 
# The skewness is a measure of the asymmetry of the distribution. 
# The kurtosis is a measure of the “tailedness” of the distribution
# A large value usually means there are more outliers.

DescribeResult(nobs=500, minmax=(np.float64(-3.14741652154398), np.float64(3.166556832560496)), mean=np.float64(-0.06456684264913627), variance=np.float64(1.000869122619677), skewness=np.float64(0.01994072341599204), kurtosis=np.float64(0.0543747243165571))


- numpy.max(array) : Returns the maximum value from the array
- numpy.std(array) : Returns the standard deviation among the values of array.
- numpy.sum(array) : Returns the sum of all the values of array.
- numpy.dot(array) : Returns the dot product of array with itself.